Creating Series

In [1]:
# Program for creating Series using series() method of Pandas Library

In [2]:
#Import Pandas library
import pandas as pd

In [3]:
#Creating Student Name List
Name=["Sanika","Aadesh","Snehal","Vedant","Shrushti"]
Name

['Sanika', 'Aadesh', 'Snehal', 'Vedant', 'Shrushti']

In [4]:
#Creating a Series 
Roll_list=pd.Series(Name,index=[1,2,3,4,5])
print(Roll_list)

1      Sanika
2      Aadesh
3      Snehal
4      Vedant
5    Shrushti
dtype: object

Creating Data Frame

In [5]:
#Import Pandas library
import pandas as pd

In [6]:
#Creating Data Frame
df=pd.DataFrame([[10,12,14,16],[11,18,15,21],[12,13,14,15]],
columns= ["CD","DBMS","DSS","CAO"])

In [7]:
df

   CD  DBMS  DSS  CAO
0  10    12   14   16
1  11    18   15   21
2  12    13   14   15

In [8]:
df.shape

(3, 4)

In [9]:
df.size

12

In [10]:
df.ndim

2

Adding Record (Row) to the data frame

In [11]:
df2=pd.DataFrame([[5,6,7,8]],
columns= ["CD","DBMS","DSS","CAO"])

In [13]:
df3 = pd.concat([df, df2], ignore_index=True)

In [14]:
df3

   CD  DBMS  DSS  CAO
0  10    12   14   16
1  11    18   15   21
2  12    13   14   15
3   5     6    7    8

Adding Attribute (Columns) name DM

In [15]:
df3["DM"]=[12,15,16,14]

In [16]:
df3

   CD  DBMS  DSS  CAO  DM
0  10    12   14   16  12
1  11    18   15   21  15
2  12    13   14   15  16
3   5     6    7    8  14

Deleting Record from df3 dataframe

In [17]:
df4=df3.drop(index=[1])

In [18]:
df4

   CD  DBMS  DSS  CAO  DM
0  10    12   14   16  12
2  12    13   14   15  16
3   5     6    7    8  14

Deleting Attribute (Columns) from df3 dataframe

In [19]:
df5=df3.drop(columns=["DM"])

In [20]:
df5

   CD  DBMS  DSS  CAO
0  10    12   14   16
1  11    18   15   21
2  12    13   14   15
3   5     6    7    8

In [21]:
#Finding mean of DSS 

print("Mean of DSS:", df5["DSS"].mean())

Mean of DSS: 12.5

In [22]:
#Finding median of DSS

print("Median of DSS:", df5["DSS"].median())

Median of DSS: 14.0