In [1]:
import pandas as pd

In [2]:
import os

In [3]:
os.getcwd()

'C:\\Users\\admin'

In [4]:
os.chdir('C:\\Users\\admin\\Desktop')

In [5]:
data=pd.read_csv("salary_data.csv")

In [6]:
data.head()

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [7]:
data.tail()

    YearsExperience    Salary
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [8]:
data.head(27)

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0

In [9]:
data.shape

(30, 2)

In [10]:
data.size

60

In [11]:
data.ndim

2

In [12]:
data.columns

Index(['YearsExperience', 'Salary'], dtype='object')

In [13]:
data.describe()

       YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [14]:
data.isnull().sum()

YearsExperience    0
Salary             0
dtype: int64

In [15]:
x=data.drop('Salary',axis=1)

In [16]:
x.head()

   YearsExperience
0              1.1
1              1.3
2              1.5
3              2.0
4              2.2

In [17]:
y=data.Salary

In [18]:
y.head()

0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
Name: Salary, dtype: float64

Line Chart

In [9]:
import pandas as pd

In [10]:
import os

In [11]:
os.chdir('C:\\Users\\admin\\Desktop')

In [12]:
data=pd.read_csv("salary_data.csv")

In [13]:
data.head()

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [14]:
x=data.YearsExperience

In [15]:
y=data.Salary

In [16]:
from sklearn.model_selection import train_test_split

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0,test_size=0.30)

In [20]:
print(x_train.shape)

(21,)

In [21]:
x_test.shape

(9,)

Model Fitting